# Jekyll
theme: linkhub-jekyll-theme

# Site Configuration
name: Ruckus Property Solutions LLC # Name of your website
tagline: Home # Set your preferred page title
description: Ruckus Property Solutions LLC is a leasing agency and property management firm based in Westminster, Colorado.
favicon:
  path: # Path / URL to the favicon of your website (e.g., 'assets/images/favicon.png')
  type: png # File format of image. Change according to your image. Supported types: https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types
logo: # Path / URL to the logo (e.g., 'assets/images/logo.png')
url: https://ruckusps.net # URL of your website
locale: en_US # The value specifies the locale in which these tags are marked up. It follows the format `language_TERRITORY`.
ga4: # Google Analytics 4 measurement ID, for e.g. G-XXXXXXX (optional). Remove it if it’s not needed.
twitter:
  username: # Used for SEO
image:
  path: # Used for SEO (og:image, twitter:image)
  type: jpeg # File format of image.
  height: 100 # Pixels
  width: 100
  alt: logo

# Verified Badge Configuration
badge:
  enable: true # Set to 'true' or 'false' to enable / disable the badge
  icon: ri:verified-badge-fill # Enter the icon name for the badge from Iconify Design (https://icon-sets.iconify.design/)
  color: '#dfb221' # Define the color of the badge

# Defaults
defaults:
- scope:
    path: ""
  values:
    layout: "default"

# Exclude
exclude: [README.md, Gemfile.lock, .jekyll-cache/, .github/, CHANGELOG.md, Gemfile, LICENSE.txt, funding.yml, linkhub-jekyll-theme.gemspec]
